// <auto-generated />
namespace Proyecto_Final.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mimigracion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mimigracion));
        
        string IMigrationMetadata.Id
        {
            get { return "202411050450206_mimigracion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
