// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Final.Models;

#nullable disable

namespace Proyecto_Final.Migrations
{
    [DbContext(typeof(ProyectoFinalContext))]
    [Migration("20241105044834_NombreDeTuMigracion")]
    partial class NombreDeTuMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_Final.Models.Admin", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAdmin");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdmin"));

                    b.Property<string>("Contraseña")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contraseña");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdAdmin")
                        .HasName("PK__Admin__B2C3ADE5F2A5DF96");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("Proyecto_Final.Models.Biblioteca", b =>
                {
                    b.Property<int>("IdBiblio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idBiblio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBiblio"));

                    b.Property<int?>("Juegos")
                        .HasColumnType("int")
                        .HasColumnName("juegos");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdBiblio")
                        .HasName("PK__Bibliote__C721831F871764D8");

                    b.HasIndex("Juegos");

                    b.ToTable("Biblioteca", (string)null);
                });

            modelBuilder.Entity("Proyecto_Final.Models.Juego", b =>
                {
                    b.Property<int>("IdJuegos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idJuegos");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJuegos"));

                    b.Property<string>("Desarrolladora")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("desarrolladora");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Genero")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("genero");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(225)
                        .IsUnicode(false)
                        .HasColumnType("varchar(225)")
                        .HasColumnName("imagenURL");

                    b.Property<int?>("ItiPlus")
                        .HasColumnType("int")
                        .HasColumnName("itiPlus");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("money")
                        .HasColumnName("precio");

                    b.HasKey("IdJuegos")
                        .HasName("PK__Juegos__E4EEF679CB006B0B");

                    b.HasIndex("ItiPlus");

                    b.ToTable("Juegos");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Membresium", b =>
                {
                    b.Property<int>("IdMembresia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMembresia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMembresia"));

                    b.Property<string>("Detalle")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("detalle");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("TipoMembresia")
                        .HasColumnType("int")
                        .HasColumnName("tipoMembresia");

                    b.HasKey("IdMembresia")
                        .HasName("PK__Membresi__BDDB80E94CDE81D8");

                    b.ToTable("Membresia");
                });

            modelBuilder.Entity("Proyecto_Final.Models.MiembrosPlu", b =>
                {
                    b.Property<int>("IdMiembros")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMiembros");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMiembros"));

                    b.Property<int?>("CantidadJuegosMembresia")
                        .HasColumnType("int")
                        .HasColumnName("cantidadJuegosMembresia");

                    b.Property<string>("FormaPago")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("formaPago");

                    b.Property<decimal?>("PrecioMembresia")
                        .HasColumnType("money")
                        .HasColumnName("precioMembresia");

                    b.Property<int?>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("Vigencia")
                        .HasColumnType("datetime")
                        .HasColumnName("vigencia");

                    b.HasKey("IdMiembros")
                        .HasName("PK__Miembros__F1261B7C5B75030D");

                    b.HasIndex("Tipo");

                    b.ToTable("MiembrosPlus");
                });

            modelBuilder.Entity("Proyecto_Final.Models.TipoMembresium", b =>
                {
                    b.Property<int>("IdTipoMembresia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTipoMembresia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoMembresia"));

                    b.Property<int?>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tipo");

                    b.HasKey("IdTipoMembresia")
                        .HasName("PK__TipoMemb__1D164B22339793F0");

                    b.HasIndex("Tipo");

                    b.ToTable("TipoMembresia");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuarios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUsuarios");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarios"));

                    b.Property<int?>("BiblioJuegos")
                        .HasColumnType("int")
                        .HasColumnName("biblioJuegos");

                    b.Property<int?>("CantJuegos")
                        .HasColumnType("int")
                        .HasColumnName("cantJuegos");

                    b.Property<string>("Contraseña")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contraseña");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<int?>("Miembro")
                        .HasColumnType("int")
                        .HasColumnName("miembro");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombreUsuario");

                    b.HasKey("IdUsuarios")
                        .HasName("PK__Usuarios__3940559A03D1B9BB");

                    b.HasIndex("BiblioJuegos");

                    b.HasIndex("Miembro");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Biblioteca", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Juego", "JuegosNavigation")
                        .WithMany("Bibliotecas")
                        .HasForeignKey("Juegos")
                        .HasConstraintName("biblio_Juego_fk");

                    b.Navigation("JuegosNavigation");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Juego", b =>
                {
                    b.HasOne("Proyecto_Final.Models.TipoMembresium", "ItiPlusNavigation")
                        .WithMany("Juegos")
                        .HasForeignKey("ItiPlus")
                        .HasConstraintName("Juegos_TipoMemb_FK");

                    b.Navigation("ItiPlusNavigation");
                });

            modelBuilder.Entity("Proyecto_Final.Models.MiembrosPlu", b =>
                {
                    b.HasOne("Proyecto_Final.Models.TipoMembresium", "TipoNavigation")
                        .WithMany("MiembrosPlus")
                        .HasForeignKey("Tipo")
                        .HasConstraintName("Plus_TipoMemb_FK");

                    b.Navigation("TipoNavigation");
                });

            modelBuilder.Entity("Proyecto_Final.Models.TipoMembresium", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Membresium", "TipoNavigation")
                        .WithMany("TipoMembresiaNavigation")
                        .HasForeignKey("Tipo")
                        .HasConstraintName("Tipo_Memb_FK");

                    b.Navigation("TipoNavigation");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Usuario", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Biblioteca", "BiblioJuegosNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("BiblioJuegos")
                        .HasConstraintName("usu_biblio_fk");

                    b.HasOne("Proyecto_Final.Models.MiembrosPlu", "MiembroNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("Miembro")
                        .HasConstraintName("Usu_Memb_fk");

                    b.Navigation("BiblioJuegosNavigation");

                    b.Navigation("MiembroNavigation");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Biblioteca", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Juego", b =>
                {
                    b.Navigation("Bibliotecas");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Membresium", b =>
                {
                    b.Navigation("TipoMembresiaNavigation");
                });

            modelBuilder.Entity("Proyecto_Final.Models.MiembrosPlu", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Proyecto_Final.Models.TipoMembresium", b =>
                {
                    b.Navigation("Juegos");

                    b.Navigation("MiembrosPlus");
                });
#pragma warning restore 612, 618
        }
    }
}
